fix convert_decompress_rm

diff --git a/source/.shell/convert_videos b/source/.shell/convert_videos
--- a/source/.shell/convert_videos
+++ b/source/.shell/convert_videos
@@ -666,6 +666,55 @@ convert_decompress_rm(){
 
 }
 
+convert_decompress_rm(){
+
+    echo review && return
+
+    echo "\e[34m ===== convert_decompress_rm $1 ===== \e[0m"
+
+    cd "$convert_dir/$1" || return
+
+    ls -lh
+
+    error=false
+
+    if [ "$(ls *.part1.rar)" != "" ]
+    then
+    	find -name '*.rar' | while read line
+    	do
+    		yes n | unrar x "`basename $line`"
+            [ $? != 0 ] && error=true && break
+    	done
+        [ $error = false ] && ls *.part*.rar | Xargs rm
+    fi
+
+    if [ "$(ls *.part01.rar)" != "" ]
+    then
+    	find -name '*.rar' | while read line
+    	do
+    		yes n | unrar x "`basename $line`"
+            [ $? != 0 ] && error=true && break
+    	done
+        [ $error = false ] && ls *.part*.rar | Xargs rm
+    fi
+
+    if [ "$(ls *.rar)" != "" ]
+    then
+        unrar x *.rar
+        [ $? != 0 ] && error=true
+        [ $error = false ] && ls *.rar | Xargs rm
+    fi
+
+    if [ $error = true ]
+    then
+        echo '\e[31m Error decompressing \e[0m'
+        pwd >> /tmp/cdr_errors
+        mv "$convert_dir/$1" "$convert_dir/$1_noconvert_decompress_error"
+        read
+    fi
+
+}
+
 convert_recursive_parallel(){
 
 	[ $# -eq 0 ] && width=720
