convert_recursive_parallel

diff --git a/source/.shell/convert_videos b/source/.shell/convert_videos
--- a/source/.shell/convert_videos
+++ b/source/.shell/convert_videos
@@ -267,6 +267,83 @@ convert_recursive(){
 
 }
 
+convert_recursive_parallel(){
+	convert_dir=/media/DATA/convert
+	converted_dir=/media/DATA/converted
+
+	convert_opts="-vf 'scale=640:trunc(ow/a/2)*2' -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level 3 -c:v libx264 -preset slow -crf 25 -c:a copy"
+
+	[ -e /usr/bin/ffmpeg ] || pkg install ffmpeg
+	[ -e /usr/bin/rar ]    || pkg install rar
+
+	rm -fr /tmp/convert_report
+
+	cd $convert_dir
+	find -name '*.rar' | while read line
+	do
+		cd "`dirname $line`"
+		yes n | unrar x "`basename $line`"
+		rm -fr "`basename $line`"
+		cd -
+	done
+
+	cd $convert_dir
+	find $PWD -type d | while read line
+	do
+		mkdir -p "`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`"
+	done
+
+	findcmd="find \$PWD -iname '*.mp4' -or -iname '*.flv' -or -iname '*.mov' -or -iname '*.avi' -or -iname '*.wmv'"
+
+	cd $convert_dir
+	rm -rf /tmp/script;
+	echo $findcmd | bash | while read line
+	do
+		echo ffmpeg -i \"$line\" `echo $convert_opts` \"`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4\" "</dev/null"  >> /tmp/script
+	done
+
+	cat /tmp/script | parallel -j`nproc` bash -c
+
+	cd $convert_dir
+	echo $findcmd | bash | while read line
+	do
+		file1="$line"
+		base1=`basename "$line"`
+		file2="`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4"
+		size1=`ls -lh "$file1" | cut -d' ' -f5`
+		size2=`ls -lh "$file2" | cut -d' ' -f5`
+		printf '%100s \e[31m %s \e[32m %s \e[0m\n' $base1 $size1 $size2 | tee -a /tmp/convert_report
+	done
+
+	cd $convert_dir
+	echo $findcmd | bash | while read line
+	do
+		file1="$line"
+		base1=`basename "$line"`
+		file2="`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4"
+		[ -e "$file2" ] || echo "\e[31m Fail converting $file1 \e[0m" | tee -a /tmp/convert_report
+	done
+
+	cd $convert_dir
+	find $PWD -type f | while read line
+	do
+		file1="$line"
+		base1="`basename "$line"`"
+		file2="$(echo "$line" | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g)"
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || echo cp \"$file1\" \"$file2\" | tee -a /tmp/convert_report
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || cp "$file1" "$file2"
+	done
+
+	cd $convert_dir
+	find $PWD -type f | while read line
+	do
+		file1="$line"
+		base1="`basename "$line"`"
+		file2="$(echo "$line" | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g)"
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || echo "\e[31m Missing file $file2 \e[0m" | tee -a /tmp/convert_report
+	done
+}
+
 mv_converted(){
 	converted_dir=/media/DATA/converted
 	[ $# -eq 1 ] && destination="$1"
