Simplifying convert_recursive

diff --git a/source/.shell/convert_videos b/source/.shell/convert_videos
--- a/source/.shell/convert_videos
+++ b/source/.shell/convert_videos
@@ -277,6 +277,94 @@ convert_recursive(){
 
 }
 
+convert_recursive(){
+
+	convert_dir=/media/DATA/convert
+	converted_dir=/media/DATA/converted
+	convert_opts="-vf 'scale=640:trunc(ow/a/2)*2' -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level 3 -c:v libx264 -preset slow -crf 25 -c:a copy"
+
+	[ -e "$convert_dir" ]   || return
+	[ -e "$converted_dir" ] || return
+
+	[ -e /usr/bin/ffmpeg ]   || pkg install ffmpeg
+	[ -e /usr/bin/unrar ]    || pkg install unrar
+
+	rm -fr /tmp/convert_report
+
+	cd $convert_dir
+	find -name '*.rar' | while read line
+	do
+		cd "`dirname $line`"
+		yes n | unrar x "`basename $line`"
+		rm -fr "`basename $line`"
+		cd -
+	done
+
+	cd $convert_dir
+	find $PWD -type d | while read line
+	do
+		mkdir -p "`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`"
+	done
+
+	findcmd="find \$PWD -iname '*.mp4' -or -iname '*.m4v' -or -iname '*.flv' -or -iname '*.mov' -or -iname '*.avi' -or -iname '*.wmv' -or -iname '*.mkv' -or -iname '*.vob'"
+
+	cd $convert_dir
+	total=`echo $findcmd | bash | wc -l`
+	actual=1;
+	echo $findcmd | bash | sort | while read line
+	do
+		echo "\e[31m ===== ($actual / $total) $line =====\e[0m"
+		actual=$(( $actual + 1 ))
+
+		[ -e "`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4" ] && continue
+
+		echo ffmpeg -i \"$line\" `echo $convert_opts` \"`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4\" "</dev/null" | bash
+
+	done
+
+	find "$converted_dir" -name 'file*.mp4' -size 0 -delete 2>/dev/null
+
+	cd $convert_dir
+	echo $findcmd | bash | while read line
+	do
+		file1="$line"
+		base1=`basename "$line"`
+		file2="`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4"
+		size1=`ls -lh "$file1" | cut -d' ' -f5`
+		size2=`ls -lh "$file2" | cut -d' ' -f5`
+		printf '%100s \e[31m %s \e[32m %s \e[0m\n' $base1 $size1 $size2 | tee -a /tmp/convert_report
+	done
+
+	cd $convert_dir
+	echo $findcmd | bash | while read line
+	do
+		file1="$line"
+		base1=`basename "$line"`
+		file2="`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4"
+		[ -e "$file2" ] || echo "\e[31m Fail converting $file1 \e[0m" | tee -a /tmp/convert_report
+	done
+
+	cd $convert_dir
+	find $PWD -type f | while read line
+	do
+		file1="$line"
+		base1="`basename "$line"`"
+		file2="$(echo "$line" | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g)"
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || echo cp \"$file1\" \"$file2\" | tee -a /tmp/convert_report
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || cp "$file1" "$file2"
+	done
+
+	cd $convert_dir
+	find $PWD -type f | while read line
+	do
+		file1="$line"
+		base1="`basename "$line"`"
+		file2="$(echo "$line" | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g)"
+		( [ -e "$file2.converted.mp4" ] || [ -e "$file2" ] ) || echo "\e[31m Missing file $file2 \e[0m" | tee -a /tmp/convert_report
+	done
+
+}
+
 convert_recursive_parallel(){
 	convert_dir=/media/DATA/convert
 	converted_dir=/media/DATA/converted
