add convert_recursive_parallel_core

diff --git a/source/.shell/convert_videos b/source/.shell/convert_videos
--- a/source/.shell/convert_videos
+++ b/source/.shell/convert_videos
@@ -664,6 +664,27 @@ convert_recursive_parallel(){
     sync
 }
 
+convert_recursive_parallel_core(){
+
+	[ $# -eq 0 ] && width=720
+	[ $# -eq 1 ] && width=$1
+	convert_opts="-vf 'scale=${width}:trunc(ow/a/2)*2' -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level 3 -c:v libx264 -preset slow -crf 25 -c:a copy -loglevel warning" # -loglevel {quiet, panic, fatal, error, warning, info, verbose, debug, trace} -hide_banner -nostats
+
+	findcmd="find \$PWD -iname '*.mp4' -or -iname '*.m4v' -or -iname '*.flv' -or -iname '*.mov' -or -iname '*.avi' -or -iname '*.wmv' -or -iname '*.mkv' -or -iname '*.vob' | grep -v noconvert"
+
+	cd $convert_dir
+	rm -fr /tmp/convert_script;
+	echo $findcmd | bash | while read line
+	do
+		[ -e "`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4" ] && continue
+		echo ffmpeg -i \"$line\" `echo $convert_opts` \"`echo $line | sed s/$(escape $convert_dir)/$(escape $converted_dir)/g`.converted.mp4\" "</dev/null"  >> /tmp/convert_script
+	done
+
+	[ `nproc` -gt 2 ] && ( cat /tmp/convert_script | parallel -j$((`nproc` - 2)) bash -c )
+	[ `nproc` -gt 2 ] || ( source /tmp/convert_script )
+
+}
+
 convert_recursive_parallel_handbrake(){
 
     convert_opts="--preset-import-file ~/config/presets.json --preset 'Very Fast 1080p30'"
